# Generated by Django 2.2.10 on 2020-03-21 03:29

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20200304_2211'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sku', models.CharField(max_length=100)),
                ('pid', models.CharField(max_length=200)),
                ('itemGroupId', models.CharField(max_length=200)),
                ('base_url', models.URLField()),
                ('name', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='products/')),
                ('startPrice', models.DecimalField(decimal_places=2, max_digits=8)),
                ('toPrice', models.DecimalField(decimal_places=2, max_digits=8)),
                ('groupPrices', models.CharField(max_length=200)),
                ('price', models.CharField(max_length=200)),
                ('salePrice', models.DecimalField(decimal_places=2, max_digits=8)),
                ('currency', models.CharField(max_length=10)),
                ('discount', models.FloatField(blank=True, default=0)),
                ('shortDesc', models.CharField(max_length=200)),
                ('desc', models.TextField(blank=True, default='Description goes here')),
                ('category', models.CharField(blank=True, max_length=200)),
                ('listCategory', models.CharField(blank=True, max_length=200)),
                ('other', models.CharField(blank=True, max_length=200)),
                ('otherAttributeToIndex', models.CharField(blank=True, max_length=200)),
                ('inStock', models.CharField(default=True, max_length=200)),
                ('rating', models.PositiveIntegerField(blank=True)),
                ('customerReview', models.CharField(blank=True, max_length=200)),
            ],
        ),
    ]
