# Generated by Django 2.2.10 on 2020-03-21 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='groupPrices',
        ),
        migrations.RemoveField(
            model_name='product',
            name='pid',
        ),
        migrations.AlterField(
            model_name='product',
            name='base_url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, height_field=True, upload_to='products/', width_field=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='itemGroupId',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='product',
            name='salePrice',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8),
        ),
        migrations.AlterField(
            model_name='product',
            name='shortDesc',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='product',
            name='startPrice',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8),
        ),
        migrations.AlterField(
            model_name='product',
            name='toPrice',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8),
        ),
    ]
